# Generated by Django 2.1.1 on 2018-10-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='last_upate',
            new_name='last_update',
        ),
    ]
