# Generated by Django 2.1.1 on 2018-11-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_topic_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='view',
            new_name='views',
        ),
    ]
